### ISSUE TITLE
默认用户名密码

### ISSUE THREAD

**Issue by chenweiask** [Verdvana/Verdvana.github.io#6]
请问你上传的AC68U的默认用户名密码是什么？

**Comment by Verdvana** [comment]
抱歉，没明白你在问啥。AC68U是华硕路由器，我没上传过路由器。如果你问的是AC68U的默认后台登陆的账号和密码，都是admin

**Comment by chenweiask** [comment]
> 抱歉，没明白你在问啥。AC68U是华硕路由器，我没上传过路由器。如果你问的是AC68U的默认后台登陆的账号和密码，都是admin

是的是的，就是问ROM包的默认用户名和密码。谢谢啦！

**Comment by Verdvana** [comment]
> > 抱歉，没明白你在问啥。AC68U是华硕路由器，我没上传过路由器。如果你问的是AC68U的默认后台登陆的账号和密码，都是admin
> 
> 是的是的，就是问ROM包的默认用户名和密码。谢谢啦！

不客气

**Comment by Verdvana** [comment]
Close
